---
- name: instalando docker
  hosts: docker
  tasks:
  - name: install a key do repositorio
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg 
  - name: add repositorio
    apt_repository:
     repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
     state: present
     update_cache: yes   ##### atualizar o repositorio antes da instalacao.
  - name: requisitos docker
    apt: 
     name: "{{item}}"
     #state: present
    with_items:
       - apt-transport-https
       - ca-certificates
       - curl
       - software-properties-common
  - name: install docker-ce
    apt:
      name: docker-ce
      state: present
